version: '3.8'
services:
  url-shortener:
    build: .
    container_name: url-shortener-container
    image: simple-link-shortener-app:latest
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./migration:/var/lib/postgresql
      - ./migration/init:/docker-entrypoint-initdb.d